services:
  info_ao_dyn_linux_gpu:
    shm_size: "5gb"
    platform: linux/amd64
    build:
      context: ../docker/pytorch_gpu
    volumes:
      - ..:/workspace:cached
      - ~/.gitconfig:/workspace/.gitconfig:ro
    environment:
      - PYTHONPATH=/workspace/python
    command: /bin/sh -c "while sleep 1000; do :; done"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [ gpu ]
